### ISSUE TITLE
azan times won't show

### ISSUE THREAD

**Issue by MoAlSeifi** [AminSallah/Flow.Launcher.Plugin.Azan#1]
salam alaikom
First of all I wanted to thank you for creating such awesome tool, (I actually was thinking of creating one myself until I found yours)

second, I'm having trouble using this tool, I have filled all necessary forms (like the image in the read
me page) and when i write azan in the search bar, it doesn't show anything.
![image_2024-05-25_040501140](https://github.com/AminSallah/Flow.Launcher.Plugin.Azan/assets/50620715/c726bc9c-e9e6-4448-a52e-b80ef806e73e)

I don't know what is wrong,

**Comment by AminSallah** [comment]
Wa Alaikum Assalam. Thank you, @MoAlSeifi, for your words. Can you please check if the API server is not blocked by your internet provider by editing the `longitude` and `latitude` values before proceeding?

```
https://api.aladhan.com/v1/calendar/2024/5?latitude=20.508515&longitude=30.1254872
```

If the status code is 200 and you are able to see the timings object in the response, copy the latitude and longitude values into the settings and remove other adjustment values such as tune and adjustment. After that, restart Flow Launcher. Let me know your results for further investigation.

**Comment by MoAlSeifi** [comment]
thanks for your response,
I tried the API URL with my own coordinates and it returned 200 status code and the timings object, it seems the API server is not blocked by my Internet Provider.
I also tried other locations and settings as well but it didn't work either.
here is my current settings:
![image](https://github.com/AminSallah/Flow.Launcher.Plugin.Azan/assets/50620715/63d59498-44dc-45c0-9d71-c3b5d1a51bdf)
are there any logs that I can look into for troubleshooting ?

**Comment by AminSallah** [comment]
Hmm, this sounds weird to me unless your device date is not calibrated please check that your machine date is aligned to today. Also open the plugin directory from the little icon under plugin settings then locate a file named `Timings.json` in the Home plugin directory. Check if this file contains an object `"timings"` within an array like this:
```
[{"timings":{ 
...
}
]
```
If this array is found, it indicates that the machine date is not calibrated. If the file is not found or is empty, let me know.

**Comment by MoAlSeifi** [comment]
I checked both my machines date, which was correct and synced (automatically), and `Timing.json` which had the timing object that contains 38000+ characters of data.
yet still it doesn't work...

**Comment by AminSallah** [comment]
Nothing comes to mind regarding the issue, but it may be related to the machine's date or possibly a cultural variation. This could occur if the machine language is not set to en-US. This issue should be addressed in the new version. If the plugin doesn't work with default options after updating, locate `DataQuerySpan` in the plugin settings and set it to `yearly`. This should resolve the issue. 
If it persists for any reason you should see an error message, and your settings will be logged in the plugin directory in `Azan.Log.json`. Please share the contents of this file with me for further investigation.

**Comment by MoAlSeifi** [comment]
I just Updated the plugin and it works flawlessly!
I want to thank you brother for this awesome tool and your patience for resolving the my problem.🤲
