### ISSUE TITLE
plugin doesnt show any data

### ISSUE THREAD

**Issue by nabeelmoeen** [AminSallah/Flow.Launcher.Plugin.Azan#4]
HI, 
I have a fresh install of Flow.Launcher and added this plugin, but after adding the values in the configuration my instance doesn't load /show any data. 
I am sharing the configuration screenshot and the flow.launcher screenshot.

As per directions shared in issue #1 I have checked and synced the system time with windows servers.
I have also validated the api url returns a valid 200 response code.

But the timings.json file in the plugin directory is a blank json object: {}

<img width="652" alt="azan config" src="https://github.com/AminSallah/Flow.Launcher.Plugin.Azan/assets/6676242/8ac8cc09-def6-44b0-9b75-03e28f340538">

<hr>
<img width="452" alt="azan " src="https://github.com/AminSallah/Flow.Launcher.Plugin.Azan/assets/6676242/0bf52ad7-1e8a-4283-b48f-afc01d79aca5">

**Comment by nabeelmoeen** [comment]
btw, the timings.json file is not modified since the installation 2 days ago.

**Comment by AminSallah** [comment]
Hey Nabeel, Thanks for your detailed report. It looks like you've created a new geography by flipping the coordinates. Could you please switch the longitude value with the latitude value and vice versa? or if your machine has a GPS remove the coordinates then start the plugin while running the GPS.

**Comment by nabeelmoeen** [comment]
awesome, thanks, that fixed it.
didn't realise it, just copy pasted in the order I got the coordinates from google maps :)

**Comment by AminSallah** [comment]
Glad that helped. Closing this for now. Feel free to reopen if further discussion is required.
